### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by murandot** [murandot/protospace-37979#1]
#URL
https://protospace-37979.herokuapp.com/

**Comment by yusuketono** [comment]
@murandot さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
##### ユーザー管理機能
- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
「さん」が抜けているので、修正しましょう。

##### プロトタイプ一覧表示機能
- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
画像をクリックしてもトップページに留まってしまうため、画像をクリックしても詳細ページに遷移するように修正しましょう。

##### コメント機能
- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
エラー画面に遷移してしまうので、その場に留まるように修正しましょう。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by murandot** [comment]
ご指摘ありがとうございます。
該当箇所を確認して修正しました。
再度ご確認よろしくお願いします。

**Comment by yusuketono** [comment]
@murandot さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
